### ISSUE TITLE
Renamed composer package name is creating issues for docs.typo3.org

### ISSUE THREAD

**Issue by DanielSiepmann** [buepro/typo3-flux_elements#1]
Hello,

it looks like the composer package was renamed from `buepro/typo3-flux-elements` to `buepro/typo3-flux_elements`. This creates issues for docs.typo3.org.

Please answer here which version of the naming you wanna use.
We will remove the other variant.

Also note that this might create extra fork for you and the docs team.

**Comment by buepro** [comment]
Hello Daniel,

I am sorry for this. The composer package name is `buepro/typo3-flux-elements`.

So far I followed the rule to prefix contributions to `TYPO3` with `typo3-`. At github the name would be (e.g. `typo3-extension_name`) where the composer package name would be `typo3-extension-name`. The naming difference is reflected in `composer.json` as following:

```
{
    "name": "buepro/typo3-extension-name",
    ...
    "replace": {
        "extension_name": "self.version",
        "typo3-ter/extension-name": "self.version"
    },
    "extra": {
        "typo3/cms": {
            "extension-name": "extension_name"
        }
    }
```

Does this naming convention cause any extra work at the doc team side?

**Comment by DanielSiepmann** [comment]
Ok, thanks for feedback.
I'll remove `buepro/typo3-flux_element` from docs.typo3.org (which was not approved yet).
The existing version `buepro/typo3-flux-elements` will be kept.

If you encounter any issues due to deletion of the underscore version, just comment here and I'll take care.
