### ISSUE TITLE
Error on Typo3 v10

### ISSUE THREAD

**Issue by JavierVelazquez** [buepro/typo3-flux_elements#2]
Hello all, I have a new clean Typo3 install v10.4.2 with Bootstrap Package, console and save and close. As soon as I install Flux-element it goes wrong. I get the following error : " Return value of TYPO3\CMS\Extbase\Utility\LocalizationUtility::getLanguageService() must be an instance of TYPO3\CMS\Core\Localization\LanguageService, null returned" . I run the install tool and repaired the database. Checked for broken extensions... I tried installing it before Bootstrap package and after... same result. Any ideas? Thank you!!
I did install it because it was listes in the TER as v10 compatible... should I wait?

**Comment by buepro** [comment]
Currently `flux` is available up to TYPO3 10.2.99. The error might be related to that. `Flux_elements` was tested with the latest [development branch](https://github.com/FluidTYPO3/flux/) which should be compatible up to TYPO3 10.4.99.

**Comment by JavierVelazquez** [comment]
Thank you very much for your answer Buepro! I will have patience and wait... Thanks.
