### ISSUE TITLE
User Rights for content-type options

### ISSUE THREAD

**Issue by Inovanet** [buepro/typo3-flux_elements#3]
Is there an option or workaround to give a non admin user access to adjust the CE options?
Like set the 3 column element to handle content by 25% 50% 25%.
The options are not available.
![Content-type options](https://user-images.githubusercontent.com/25638983/96888072-85a01980-1485-11eb-977a-1bae091e55cb.JPG)

**Comment by buepro** [comment]
Such a behaviour has been reported [here](https://github.com/FluidTYPO3/flux/issues/1585). The issue has been corrected accordingly in release [1.1.1](url).
